name: Build && Deploy for release

on:
  release:
    types: [released]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all history of all tags and branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Build the package
        run: ./gradlew clean build

      - name: Get version tag
        if: success()
        run: |
          echo "VER=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Print version tag
        run: |
          echo ${{ env.VER }}

  DeployDev:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Fetch all history of all tags and branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version tag
        if: success()
        run: |
          echo "VER=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Print version tag
        run: |
          echo ${{ env.VER }}

