name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: tonynguyenit18/github-action-custom-vars@v1

      - name: Display current version
        id: cvBefore
        run: |
          echo $RECENT_MERGED_BRANCH_NAME
          ./gradlew cV

      - name: Release
        run: |
          if [[ $RECENT_MERGED_BRANCH_NAME == major* ]]; then
              ./gradlew release -Prelease.versionIncrementer=incrementMajor -Prelease.disableChecks
          elif [[ $RECENT_MERGED_BRANCH_NAME == minor* ]]; then
              ./gradlew release -Prelease.versionIncrementer=incrementMinor -Prelease.disableChecks
          elif [[ $RECENT_MERGED_BRANCH_NAME == hotfix* ]]; then
              ./gradlew release -Prelease.versionIncrementer=incrementPatch -Prelease.disableChecks
          fi

      - name: Get current version
        id: cvAfter
        run: |
          echo "RELEASE_VER=v-$(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_ENV

      - name: Print current version
        run: |
          echo ${{ env.RELEASE_VER }}

  DeployDev:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Fetch all history of all tags and branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current version
        id: cvAfter
        run: |
          ./gradlew cV -q -Prelease.quiet
          echo "RELEASE_VER=v-$(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_ENV

      - name: Print current version
        run: |
          echo ${{ env.RELEASE_VER }}

      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: engineering-notification-dev
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'account-service: ${{ env.RELEASE_VER }}'
          SLACK_TITLE: STAGE Deployment
          SLACK_USERNAME: Github Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
