name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      forceVersion:
        description: 'Force version'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get branch name and SHA
        if: success()
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | sed -e 's/\//\-/')" >> $GITHUB_ENV

      - name: Display current version
        id: cvBefore
        run: |
          ./gradlew cV

      - name: Release
        run: |
          ./gradlew release \
          -Prelease.disableChecks
          -Prelease.pushTagsOnly \
          -Prelease.overriddenBranchName=${{ env.BRANCH_NAME }}

      - name: Display current version
        id: cvAfter
        run: |
          ./gradlew cV
