name: release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request'}} && ${{ github.event.action == 'closed' }} && ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout head
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get branch name and SHA
        if: success()
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | sed -e 's/\//\-/')" >> $GITHUB_ENV

      - name: Display current version
        id: cvBefore
        run: |
          echo $GITHUB_REF
          echo ${{ github.base_ref }}
          echo ${{ env.BRANCH_NAME }}
          ./gradlew cV

      - name: Release
        run: |
          ./gradlew release \
          -Prelease.disableChecks \
          -Prelease.overriddenBranchName=${{ env.BRANCH_NAME }}

      - name: Display current version
        id: cvAfter
        run: |
          ./gradlew cV
