name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: tonynguyenit18/github-action-custom-vars@v1

      - name: Display current version
        id: cvBefore
        run: |
          echo $RECENT_MERGED_BRANCH_NAME
          ./gradlew cV

      - name: Release
        run: |
          ./gradlew release \
          -Prelease.disableChecks \
          -Prelease.pushTagsOnly \
          -Prelease.overriddenBranchName=$RECENT_MERGED_BRANCH_NAME

      - name: Display current version
        id: cvAfter
        run: |
          ./gradlew cV
