name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: tonynguyenit18/github-action-custom-vars@v1

      - name: Display current version
        id: cvBefore
        run: |
          echo $RECENT_MERGED_BRANCH_NAME
          ./gradlew cV

      - name: Release
        run: |
          if [[ $RECENT_MERGED_BRANCH_NAME == major* ]]; then
              echo "majorrrrr"
              ./gradlew release -Prelease.versionIncrementer=incrementMajor -Prelease.disableChecks
          elif [[ $RECENT_MERGED_BRANCH_NAME == minor* ]]; then
              echo "minorrrrr"
              ./gradlew release -Prelease.versionIncrementer=incrementMinor -Prelease.disableChecks
          elif [[ $RECENT_MERGED_BRANCH_NAME == hotfix* ]]; then
              echo "patchhhhh"
              ./gradlew release -Prelease.versionIncrementer=incrementPatch -Prelease.disableChecks
          else
              echo "elseeeee"
          fi

      - name: Get current version
        id: cvAfter
        run: |
          echo "RELEASE_VER=v-$(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_ENV

      - name: Print current version
        run: |
          echo ${{ env.RELEASE_VER }}

  DeployDev:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Fetch all history of all tags and branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current version
        id: cvAfter
        run: |
          ./gradlew cV -q -Prelease.quiet
          echo "RELEASE_VER=v-$(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_ENV

      - name: Print current version
        run: |
          echo ${{ env.RELEASE_VER }}
